GET http://localhost:3002/api/persons

###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "morty",
    "number": "21632-3243"
}

###

POST http://localhost:3002/api/users
Content-Type: application/json

{
    "username": "sike",
    "name": "sike xu",
    "password": "1234567"
}
